--1. List all Categories and the number of Products in each. Include categories with zero products.

SELECT c.CategoryName, COUNT(p.ProductID) AS TotalProducts
FROM Categories c
LEFT JOIN Products p ON c.CategoryID = p.CategoryID
GROUP BY c.CategoryID, c.CategoryName;

--2. Find Products that have never been ordered.

SELECT p.ProductName
FROM Products p
LEFT JOIN OrderItems oi ON p.ProductID = oi.ProductID
WHERE oi.ItemID IS NULL;

--3. Show the Total Revenue (Price * Quantity) generated by each Category.

SELECT c.CategoryName, SUM(p.Price * oi.Quantity) AS TotalRevenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN OrderItems oi ON p.ProductID = oi.ProductID
GROUP BY c.CategoryID, c.CategoryName;

--4. List the Names of Customers who have ordered products from the 'Electronics' category.


-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--5. Find Orders where the total quantity of items is greater than 10

SELECT OrderID, COUNT(Quantity) AS TotalQuantity
FROM OrderItems
GROUP BY OrderID
HAVING COUNT(Quantity) > 10;




-- 1. List all Lawyers and their total file storage. If a lawyer has no files, show 0 instead of NULL

SELECT l.Name, COALESCE(SUM(d.FileSizeKB), 0) AS TotalFileStorage
FROM Lawyers l
LEFT JOIN Matters m ON l.LawyerID = m.LeadLawyerID
GROUP BY l.LawyerID, l.Name;


-- 2. Find the Names of Lawyers who have at least one Matter, but that Matter has zero documents.

SELECT DISTINCT l.Name
FROM Lawyers l
JOIN Matters m ON l.LawyerID = m.LeadLawyerID
LEFT JOIN Documents d ON m.MatterID = d.MatterID
WHERE d.DocID IS NULL;

-- 3. Calculate total documents per Lawyer, ensuring that if two lawyers have the same name, they are not combined.

SELECT l.LawyerID, l.Name, COUNT(d.DocID) AS TotalDocuments
FROM Lawyers l
LEFT JOIN Matters m ON l.LawyerID = m.LeadLawyerID
LEFT JOIN Documents d ON m.MatterID = d.MatterID
GROUP BY l.LawyerID, l.Name;

-- 4. List Matters that have a total file size greater than 10,000 KB, 
--but ignore any individual documents that are smaller than 100 KB in that calculation.

SELECT m.Title, SUM(d.FileSizeKB) AS TotalFileSize
FROM Matters m
JOIN Documents d ON m.MatterID = d.MatterID
WHERE d.FileSizeKB >= 100
GROUP BY m.Title 
HAVING SUM(d.FileSizeKB) > 10000;


--5. List all Lawyers and any Matters they lead with 'Litigation' in the title. Lawyers with no 'Litigation' matters must still 
-- appear in the list.

--6. Find the average document size (FileSizeKB) for each Department.

SELECT l.Department, AVG(d.FileSizeKB) AS AvgDocSize
FROM Lawyers l
JOIN Matters m ON l.LawyerID = m.LeadLawyerID
JOIN Documents d ON m.MatterID = d.MatterID
GROUP BY l.Department;

-- Schema Details:
-- Lawyers (LawyerID, Name, Department)
-- Matters (MatterID, Title, LeadLawyerID)
-- Documents (DocID, MatterID, FileSizeKB)

-- 7. Find the single largest document (highest FileSizeKB) for each Department. Show the Department name, the Document ID, and the size.

WITH RankedDocuments AS(
    SELECT l.Department, d.DocID, d.FileSizeKB,
        ROW_NUMBER() OVER(PARTITION BY l.Department ORDER BY d.FileSizeKB DESC) AS DocumentSizes
    FROM Lawyers l
    JOIN Matters m ON l.LawyerID = m.LeadLawyerID
    JOIN Documents d ON m.MatterID = d.MatterID
)
SELECT Department, DocID, FileSizeKB
FROM RankedDocuments
WHERE DocumentSizes = 1;