--1. List all Categories and the number of Products in each. Include categories with zero products.

--2. Find Products that have never been ordered.

--3. Show the Total Revenue (Price * Quantity) generated by each Category.

--4. List the Names of Customers who have ordered products from the 'Electronics' category.

SELECT DISTINCT o.CustomerName
FROM Orders o 
JOIN OrderItems oi ON o.OrderID = oi.OrderID
JOIN Products p ON oi.ProductID = p.ProductID
JOIN Categories c ON p.CategoryID = c.CategoryID
WHERE c.CategoryName = 'Electronics';

--5. Find Orders where the total quantity of items is greater than 10

SELECT oi.OrderID, COUNT(oi.Quantity) AS TotalQuantity
FROM OrderItems oi
GROUP BY oi.OrderID 
HAVING COUNT(oi.Quantity) > 10;


-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--7. Find the most expensive Product in each Category (using a Window Function)

-- 1. Define the CTE at the top
WITH ProductsPrices AS (
    SELECT c.CategoryName, p.ProductName, p.Price,
           ROW_NUMBER() OVER(
               PARTITION BY p.CategoryID --Whenever you use a Window Function inside a multi-table query, always try to partition and order by columns that live on the exact same table. Keeping your window definitions confined to a single table (in this case, Products) makes it much easier for the SQL optimizer to leverage existing indexes.
               ORDER BY p.Price DESC
           ) AS rnk
    FROM Categories c
    JOIN Products p ON c.CategoryID = p.CategoryID
)
-- 2. Query the CTE down below
SELECT CategoryName, ProductName, Price
FROM ProductsPrices
WHERE rnk = 1;

SELECT CategoryName, ProductName, Price --The outer query only sees these plain columns
FROM (
    -- INNER QUERY (Subquery): This runs first to gather the data and rank it
    SELECT 
        c.CategoryName, 
        p.ProductName, 
        p.Price,
        
        -- THE WINDOW FUNCTION:
        ROW_NUMBER() OVER(
            PARTITION BY c.CategoryID -- Group 1: Splits all products into virtual "piles" by their Category ID
            ORDER BY p.Price DESC     -- Group 2: Sorts the products *inside* each pile from highest price to lowest
        ) as rnk                      -- Group 3: Assigns a sequential number to each row in that pile (#1 is the most expensive)
        
    FROM Categories c
    JOIN Products p ON c.CategoryID = p.CategoryID -- Standard inner join to pair products with their category names
) t -- "t" is just an alias name given to this temporary subquery table so the outer query can read it
WHERE rnk = 1;



-- Schema Details:
-- Lawyers (LawyerID, Name, Department)
-- Matters (MatterID, Title, LeadLawyerID)
-- Documents (DocID, MatterID, FileSizeKB)

----5. List all Lawyers and any Matters they lead with 'Litigation' in the title. Lawyers with no 'Litigation' matters must still 
-- appear in the list.

SELECT l.Name, m.Title
FROM Lawyers l 
LEFT JOIN Matters m ON l.LawyerID = m.LeadLawyerID
AND m.Title LIKE '%Litigation%';





--1. Find the FullName and SubmissionDate of all candidates who submitted their details in January 2026.

SELECT FullName, SubmissionDate
FROM Candidates
WHERE SubmissionDate >= '2026-01-01' 
    AND SubmissionDate < '2026-02-01';

--2. List the FullName of the candidate, the CheckType, and the Status for all individual checks that have been 'Flagged'.

SELECT c.FullName, v.CheckType, v.Status
FROM Candidates c
JOIN Verifications v ON c.CandidateID = v.CandidateID
WHERE v.Status = 'Flagged';

--3. Find the CompanyName and the total sum of CostZAR spent on all verifications ordered by that client.

SELECT c.CompanyName, SUM(v.CostZAR) AS TotalSpent
FROM Clients cl
JOIN Candidates ca ON cl.ClientID = ca.ClientID
JOIN Verifications v ON ca.CandidateID = v.CandidateID
GROUP BY cl.ClientID, cl.CompanyName;

--4. Display the Industry name and the total count of candidates submitted under each industry.

--6. Return the CandidateID and FullName of any candidate who has at least one check with a 'Pending' status, but completely exclude candidates who have any checks 
-- with a 'Flagged' status.

SELECT c.CandidateID, c.FullName
FROM Candidates c 
JOIN Verifications p ON c.CandidateID = p.CandidateID AND p.Status = 'Pending'
LEFT JOIN Verifications f ON p.CandidateID = f.CandidateID AND f.Status = 'Flagged'
WHERE f.CandidateID IS NULL;

--6. Return the CandidateID and FullName of any candidate who has at least one check with a 'Pending' status, but completely exclude candidates who have any checks 
-- with a 'Flagged' status.

SELECT c.CandidateID, c.FullName
FROM Candidates c
JOIN Verifications p ON c.CandidateID = p.CandidateID AND p.Status = 'Pending'
LEFT JOIN Verifications f ON c.CandidateID = f.CandidateID AND f.Status = 'Flagged'
WHERE f.Status IS NULL;

SELECT DISTINCT 
    c.CandidateID, 
    c.FullName
FROM Candidates c
JOIN Verifications p ON c.CandidateID = p.CandidateID AND p.Status = 'Pending' -- filters candidate pool to only include individuals who have at least one 'Pending' check
LEFT JOIN Verifications f ON c.CandidateID = f.CandidateID AND f.Status = 'Flagged' --find only the 'Flagged' checks for those exact same candidates.
WHERE f.CandidateID IS NULL; --drop anyone who has a flagged status

-- Schema Details:
-- Clients (ClientID, CompanyName, Industry)
-- Candidates (CandidateID, ClientID, FullName, SubmissionDate)
-- Verifications (CheckID, CandidateID, CheckType, CostZAR, Status)
-- VerificationLogs (LogID, CheckID, ActionTaken, LogTimestamp)

--7. Find the CompanyName of clients whose average verification check cost (CostZAR) across all their candidates is strictly greater than 200.00.

SELECT cl.CompanyName, AVG(v.CostZAR) AS AverageVerificationCheckCost
FROM Clients cl
JOIN Candidates ca ON cl.ClientID = ca.ClientID
JOIN Verifications v ON ca.CandidateID = v.CandidateID
GROUP BY cl.CompanyName
HAVING AVG(v.CostZAR) > 200;

--9. Write a query to show the CandidateID, CheckType, and CostZAR, alongside a new column displaying the average cost of that specific CheckType across the entire 
-- database.

SELECT CandidateID, CheckType, CostZAR,
    AVG(CostZAR) OVER(PARTITION BY CheckType) AS AverageCost
FROM Verifications;

-- Schema Details:
-- Clients (ClientID, CompanyName, Industry)
-- Candidates (CandidateID, ClientID, FullName, SubmissionDate)
-- Verifications (CheckID, CandidateID, CheckType, CostZAR, Status)
-- VerificationLogs (LogID, CheckID, ActionTaken, LogTimestamp)

--10. Select the CandidateID, FullName, and SubmissionDate, along with a column that assigns a sequential row number to candidates for each unique client, 
-- ordered by their SubmissionDate from earliest to latest.

SELECT CandidateID, FullName, SubmissionDate,
    ROW_NUMBER() OVER(PARTITION BY ClientID ORDER BY SubmissionDate ASC) AS OrdersBySubmissionDate
FROM Candidates;