--1. List all Categories and the number of Products in each. Include categories with zero products.

--2. Find Products that have never been ordered.

--3. Show the Total Revenue (Price * Quantity) generated by each Category.

--4. List the Names of Customers who have ordered products from the 'Electronics' category.

SELECT DISTINCT o.CustomerName
FROM Orders o 
JOIN OrderItems oi ON o.OrderID = oi.OrderID
JOIN Products p ON oi.ProductID = p.ProductID
JOIN Categories c ON p.CategoryID = c.CategoryID
WHERE c.CategoryName = 'Electronics';

--5. Find Orders where the total quantity of items is greater than 10

SELECT oi.OrderID, COUNT(oi.Quantity) AS TotalQuantity
FROM OrderItems oi
GROUP BY oi.OrderID 
HAVING COUNT(oi.Quantity) > 10;


-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--7. Find the most expensive Product in each Category (using a Window Function)

-- 1. Define the CTE at the top
WITH ProductsPrices AS (
    SELECT c.CategoryName, p.ProductName, p.Price,
           ROW_NUMBER() OVER(
               PARTITION BY p.CategoryID --Whenever you use a Window Function inside a multi-table query, always try to partition and order by columns that live on the exact same table. Keeping your window definitions confined to a single table (in this case, Products) makes it much easier for the SQL optimizer to leverage existing indexes.
               ORDER BY p.Price DESC
           ) AS rnk
    FROM Categories c
    JOIN Products p ON c.CategoryID = p.CategoryID
)
-- 2. Query the CTE down below
SELECT CategoryName, ProductName, Price
FROM ProductsPrices
WHERE rnk = 1;

SELECT CategoryName, ProductName, Price --The outer query only sees these plain columns
FROM (
    -- INNER QUERY (Subquery): This runs first to gather the data and rank it
    SELECT 
        c.CategoryName, 
        p.ProductName, 
        p.Price,
        
        -- THE WINDOW FUNCTION:
        ROW_NUMBER() OVER(
            PARTITION BY c.CategoryID -- Group 1: Splits all products into virtual "piles" by their Category ID
            ORDER BY p.Price DESC     -- Group 2: Sorts the products *inside* each pile from highest price to lowest
        ) as rnk                      -- Group 3: Assigns a sequential number to each row in that pile (#1 is the most expensive)
        
    FROM Categories c
    JOIN Products p ON c.CategoryID = p.CategoryID -- Standard inner join to pair products with their category names
) t -- "t" is just an alias name given to this temporary subquery table so the outer query can read it
WHERE rnk = 1;