-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--1. List all Categories and the number of Products in each. Include categories with zero products.

SELECT c.CategoryName, COUNT(p.ProductID) AS ProductsCount
FROM Categories c
LEFT JOIN Products p ON c.CategoryID = p.CategoryID
GROUP BY c.CategoryID, c.CategoryName;  
--grouping by the ID ensures that if two different categories accidentally have the same name, they aren't merged into one row.


--2. Find Products that have never been ordered.

SELECT p.ProductName, oi.OrderID
FROM Products p
LEFT JOIN OrderItems oi ON p.ProductID = oi.ProductID
WHERE oi.ItemID IS NULL;

-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--3. Show the Total Revenue (Price * Quantity) generated by each Category.
--my try:
SELECT c.CategoryName, (p.Price * oi.Quantity) AS TotalRevenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN OrderItems oi ON p.ProductID = oi.ProductID;

--answer:
SELECT c.CategoryName, SUM(p.Price * oi.Quantity) AS TotalRevenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN OrderItems oi ON p.ProductID = oi.ProductID
GROUP BY c.CategoryName;

-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--4. List the Names of Customers who have ordered products from the 'Electronics' category.

SELECT DISTINCT o.CustomerName
FROM Orders o
JOIN OrderItems oi ON o.OrderID = oi.OrderID
JOIN Products p ON oi.ProductID = p.ProductID
JOIN Categories c ON c.CategoryID = p.CategoryID
WHERE c.CategoryName = 'Electronics';


-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--5. Find Orders where the total quantity of items is greater than 10

SELECT oi.OrderID, COUNT(oi.Quantity) AS QuantityCount
FROM OrderItems oi
GROUP BY oi.OrderID
HAVING COUNT(oi.Quantity) > 10;
-- didnt have to join here despite answer query having a join
-- If an interviewer gives you a question like Q5 and you catch this shortcut, you immediately stand out as an Intermediate Engineer 
-- because you are actively thinking about Performance and Efficiency.
-- Cuts database work in half. It reads from a single table, bypassing the expensive join overhead entirely.

-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--6. Show every Product and its Category. If a product has no category (NULL CategoryID), show 'Uncategorized' using COALESCE.

SELECT p.ProductName, COALESCE(c.CategoryName, 'Uncategorized') AS CategoryName
FROM Products p
LEFT JOIN Categories c ON p.CategoryID = c.CategoryID;


-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--------------------------------------------7. Find the most expensive Product in each Category (using a Window Function).

--try:
SELECT c.CategoryName, 
       p.ProductName,
       MAX(p.Price) OVER( PARTITION BY c.CategoryName) AS Most_Expensive_Product
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
GROUP BY c.CategoryID, MAX(p.Price);

-- Categories (CategoryID, CategoryName)
-- Products (ProductID, ProductName, CategoryID, Price)
-- Orders (OrderID, OrderDate, CustomerName)
-- OrderItems (ItemID, OrderID, ProductID, Quantity)

--answer:
-- OUTER QUERY: This runs last to select the clean, filtered results from our temporary set
SELECT CategoryName, ProductName, Price --The outer query only sees these plain columns
FROM (
    -- INNER QUERY (Subquery): This runs first to gather the data and rank it
    SELECT 
        c.CategoryName, 
        p.ProductName, 
        p.Price,
        
        -- THE WINDOW FUNCTION:
        ROW_NUMBER() OVER(
            PARTITION BY c.CategoryID -- Group 1: Splits all products into virtual "piles" by their Category ID
            ORDER BY p.Price DESC     -- Group 2: Sorts the products *inside* each pile from highest price to lowest
        ) as rnk                      -- Group 3: Assigns a sequential number to each row in that pile (#1 is the most expensive)
        
    FROM Categories c
    JOIN Products p ON c.CategoryID = p.CategoryID -- Standard inner join to pair products with their category names
) t -- "t" is just an alias name given to this temporary subquery table so the outer query can read it
WHERE rnk = 1; -- THE FILTER: Throws away ranks 2, 3, 4 etc., keeping only the single most expensive product per pile

--Inner Query: Has access to c and p because they are explicitly joined inside it.
--Outer Query: Only has access to t and the specific columns exposed by the inner SELECT list.